name: Java CI

on:
  push:
    - story/501

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Customer Service
        working-directory: ExampleCustomerService
        run: mvn clean package

      - name: Build Loan Service
        working-directory: ExampleLoanService
        run: mvn clean package

      - name: Build Eureka Server
        working-directory: ExampleEurekaServer
        run: mvn clean package